---
- name: IPython debug leftover
  pattern: IPython\.embed()
  filePattern: .*\.py$
  hint: Remove IPython.embed() debugging statements before committing
  error: true

# Cursor Rules Linting Rules
- name: v1 Cursor rule file in wrong location
  pattern: "^---\n(?:.*\n)+?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: "Cursor rule files (.mdc) must be placed in the .cursor/rules/ directory"
  error: true
  exclude: \.cursor/rules/.*\.mdc$|\.relint\.yml$

- name: v1 Cursor rule with wrong extension
  pattern: "^---\n(?:.*\n)+?---"
  filePattern: .*\.mdc\.md$
  hint: "Cursor rule files should use .mdc extension, not .mdc.md"
  error: true
  exclude: \.relint\.yml$

- name: v1 Missing alwaysApply in frontmatter
  pattern: "^---\n(?!(?:.*\n)*?alwaysApply:(?:.*\n)+?---)(?:.*\n)+?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: "Cursor rule files must include 'alwaysApply: true' or 'alwaysApply: false' in frontmatter"
  error: true
  exclude: \.relint\.yml$

- name: v1 Quoted glob patterns in frontmatter
  pattern: "^---\n(?:(?!---).)*?globs:(?:.*?[\"'].*?[\"'].*?\n)(?:(?!---).)*?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: |
    Glob patterns in cursor rules should be unquoted:
    Use `globs: *.py` instead of `globs: "*.py"`
  error: true
  exclude: \.relint\.yml$

- name: v1 Array notation for globs in frontmatter
  pattern: "^---\n(?:(?!---).)*?globs:\\s*\\[(?:(?!---).)*?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: |
    Glob patterns in cursor rules should use comma-separated values, not array notation:
    Use `globs: *.py, *.md` instead of `globs: ["*.py", "*.md"]`
  error: true
  exclude: \.relint\.yml$

- name: v1 Missing spaces after commas in globs
  pattern: "^---\n(?:(?!---).)*?globs:.*?,\\S(?:(?!---).)*?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: |
    Glob patterns in cursor rules should have spaces after commas:
    Use `globs: *.py, *.md` instead of `globs: *.py,*.md`
  error: true
  exclude: \.relint\.yml$

- name: v1 Curly brace notation in globs
  pattern: "^---\n(?:(?!---).)*?globs:.*?\\{.*?\\}(?:(?!---).)*?---"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: |
    Glob patterns in cursor rules should use comma-separated values, not curly brace notation:
    Use `globs: *.py, *.js, *.ts` instead of `globs: *.{py,js,ts}`
  error: true
  exclude: \.relint\.yml$

- name: v1 Missing rule tag
  pattern: "^---\n(?:.*\n)+?---\n(?:(?!<rule>).)*$"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: "Cursor rule files must include a <rule> tag"
  error: true
  exclude: \.relint\.yml$

- name: v1 Missing rule name after tag
  # Match <rule> tag not followed by name: within 5 lines
  pattern: "<rule>(?:\n[^\n]*){0,5}(?!.*name:)"
  filePattern: .*\.(mdc|mdc\.md)$
  hint: "Cursor rule must include a name field immediately after the <rule> tag"
  error: true
  exclude: \.relint\.yml$

# v2 Cursor Rules Linting Rules based on bmadcode/cursor-auto-rules-agile-workflow
- name: "v2 Frontmatter Format"
  pattern: "^---\n(description:.*\nglobs:.*\nalwaysApply:.*\n)?---\n"
  hint: "MDC files must start with frontmatter containing description, globs, and alwaysApply fields"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 Rule Title Format"
  pattern: "^---.*?---\n\n# [A-Z].*?\n"
  hint: "MDC files must have a top-level title starting with #"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 Required Sections"
  pattern: "## Context.*?## Critical Rules.*?## Examples"
  hint: "MDC files must contain Context, Critical Rules, and Examples sections in order"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 Example Format"
  pattern: "<example>.*?</example>"
  hint: "MDC files must contain at least one example section"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 Invalid Example Format"
  pattern: '<example type="invalid">.*?</example>'
  hint: "MDC files must contain at least one invalid example section"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 File Naming Convention"
  pattern: "^.*/(.*-(?:auto|agent|manual|always)\\.mdc)$"
  hint: "MDC files must end with -auto.mdc, -agent.mdc, -manual.mdc, or -always.mdc"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: true

- name: "v2 Line Count Warning"
  pattern: "(?s).{2000,}"
  hint: "MDC files should ideally be under 50 lines, better under 25 lines"
  filePattern: "\\.cursor/rules/[^/]+/.*\\.mdc$"
  error: false
